server:
  port: 9001
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://192.168.70.140:3306/security?serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false
  main:
    allow-bean-definition-overriding: true    #这个表示允许我们覆盖OAuth2放在容器中的bean对象，一定要配置
  configuration:
    map-underscore-to-camel-case: true
mybatis:
  type-aliases-package: com.itheima.oauth_server.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
